from enum import Enum


class ActionType(str, Enum):
    ASK_CLARIFYING_QUESTION = "ASK_CLARIFYING_QUESTION"
    RETRIEVE_DOCS = "RETRIEVE_DOCS"
    ESCALATE_TO_HUMAN = "ESCALATE_TO_HUMAN"
    UPGRADE_MODEL = "UPGRADE_MODEL"
    TRIGGER_WORKFLOW = "TRIGGER_WORKFLOW"
